# Site Settings
theme: jekyll-theme-architect
title: From Page to Screen – The Journey and Success of Book Adaptations
description: An interactive data story exploring the success of book adaptations.
show_downloads: true
permalink: pretty

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation Structure
navigation:
  - title: "Introduction"
    url: "/"
  - title: "The Origins"
    url: "/origins"
  - title: "The Path to Adaptation"
    url: "/path-to-adaptation"
  - title: "The Grand Premiere"
    url: "/grand-premiere"
  - title: "The Global Reception"
    url: "/global-reception"
  - title: "Budget and Investment Dilemma"
    url: "/budget-investment"
  - title: "Plot Twist"
    url: "/plot-twist"

# Default Layout Settings
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"