theme: jekyll-theme-architect
title: From Page to Screen – The Journey and Success of Book Adaptations
show_downloads: false
navigation:
  - title: "Introduction"
    url: /
  - title: "The Origins"
    url: /origins.html
  - title: "The Path to Adaptation"
    url: /path-to-adaptation.html
  - title: "The Grand Premiere"
    url: /grand-premiere.html
  - title: "The Global Reception"
    url: /global-reception.html
  - title: "Budget and Investment Dilemma"
    url: /budget-investment.html
  - title: "Plot Twist"
    url: /plot-twist.html
